/* Generated by ffconf */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
/********************************************* jiaojinxing **********************************************/
//#define AV_HAVE_FAST_UNALIGNED 1
#define AV_HAVE_FAST_UNALIGNED 0
/********************************************* jiaojinxing **********************************************/
#endif /* AVUTIL_AVCONFIG_H */
