#ifndef __COLORMAP_H
#define __COLORMAP_H

#include "gal.h"

/*
 * http://kb.iu.edu/data/aetf.html
 */
#define COLOR_RED       	RGB(255,0,0)
#define COLOR_GREEN     	RGB(0,255,0)
#define COLOR_BLUE      	RGB(0,0,255)
#define COLOR_WHITE     	RGB(255,255,255)
#define COLOR_BLACK     	RGB(0,0,0)
#define COLOR_GRAY      	RGB(128,128,128)
#define COLOR_DARKGRAY 		RGB(169,169,169)
#define COLOR_CYAN    		RGB(0,255,255)
#define COLOR_MAGENTA   	RGB(255,0,255)
#define COLOR_BROWN    		RGB(165,42,42)
#define COLOR_LIGHTGRAY 	RGB(211,211,211)
#define COLOR_LIGHTBLUE 	RGB(173,216,230)
#define COLOR_LIGHTGREEN    RGB(144,238,144)
#define COLOR_LIGHTCYAN    	RGB(224,255,255)
#define COLOR_LIGHTRED    	RGB(205,102,102)
#define COLOR_LIGHTMAGENTA  RGB(255,119,255)
#define COLOR_YELLOW    	RGB(255,255,0)

enum{
	COLOR_TEXT,
	COLOR_3DDKSHADOW,
	COLOR_3DFACE,
	COLOR_3DHILIGHT,
	COLOR_3DLIGHT,
	COLOR_3DSHADOW,
	COLOR_ACTIVEBORDER,
	COLOR_ACTIVECAPTION,
	COLOR_APPWORKSPACE,
	COLOR_BACKGROUND,
	COLOR_BTNTEXT,
	COLOR_CAPTIONTEXT,
	COLOR_GRADIENTACTIVECAPTION,
	COLOR_GRADIENTINACTIVECAPTION,
	COLOR_GRAYTEXT,
	COLOR_HIGHLIGHT,
	COLOR_HIGHLIGHTTEXT,
	COLOR_HOTLIGHT,
	COLOR_INACTIVEBORDER,
	COLOR_INACTIVECAPTION,
	COLOR_INACTIVECAPTIONTEXT,
	COLOR_INFOBK,
	COLOR_INFOTEXT,
	COLOR_MENU,
	COLOR_MENUHILIGHT,
	COLOR_MENUBAR,
	COLOR_MENUTEXT,
	COLOR_SCROLLBAR,
	COLOR_WINDOW,
	COLOR_WINDOWFRAME,
	COLOR_WINDOWTEXT,
};

#ifdef __cplusplus
extern "C" {
#endif

pixel_type GetSysColor(int num);

#ifdef __cplusplus
} //extern "C"
#endif

#endif

