#include "colormap.h"

static pixel_type _color_map[] = {
COLOR_BLACK,
COLOR_DARKGRAY,
COLOR_GRAY,
COLOR_WHITE,
COLOR_GRAY,
COLOR_DARKGRAY,
COLOR_BLUE,
COLOR_WHITE,
COLOR_WHITE,
COLOR_WHITE,
COLOR_BLACK,
COLOR_WHITE,
COLOR_WHITE,
COLOR_GRAY,
COLOR_DARKGRAY,
COLOR_WHITE,
COLOR_WHITE,
COLOR_WHITE,
COLOR_DARKGRAY,
COLOR_DARKGRAY,
COLOR_GRAY,
COLOR_WHITE,
COLOR_WHITE,
COLOR_GRAY,
COLOR_BLUE,
COLOR_WHITE,
COLOR_BLACK,
COLOR_WHITE,
COLOR_WHITE,
COLOR_WHITE,
COLOR_BLACK,
};

pixel_type GetSysColor(int num)
{
	return _color_map[num];
}
