#ifndef __SIZEMAP_H 
#define __SIZEMAP_H 

#include "common.h"

enum{
SM_MINWIDTH,
SM_MINHEIGHT,
SM_BORDER,
SM_THICKFRAME,
SM_THINFRAME,
SM_CAPTIONY,
SM_ICONX,
SM_ICONY,
SM_MENUBARY,
SM_MENUBAROFFX,
SM_MENUBAROFFY,
SM_MENUITEMY,
SM_INTERMENUITEMX,
SM_INTERMENUITEMY,
SM_MENUITEMOFFX,
SM_MENUTOPMARGIN,
SM_MENUBOTTOMMARGIN,
SM_MENULEFTMARGIN,
SM_MENURIGHTMARGIN,
SM_MENUITEMMINX,
SM_MENUSEPARATORY,
SM_MENUSEPARATORX,
SM_SB_HEIGHT,
SM_SB_WIDTH,
SM_SB_INTERX,
SM_CXVSCROLL,
SM_CYVSCROLL,
SM_CXHSCROLL,
SM_CYHSCROLL,
SM_MINBARLEN,
SM_DEFBARLEN,
SM_ITEM_NUMBER,
SM_CLOSE_BOX,
SM_CHECK_BOX,
SM_MENU_UPDOWN_ARROW_HEIGHT,
MAX_SYS_METRICS,
};

#ifdef __cplusplus
extern "C" {
#endif

int GetSysSize(int num);

#ifdef __cplusplus
} //extern "C"
#endif

#endif

